version: '3.8'
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '3007:3007'
    volumes:
     - ./server:/app
     - /app/node_modules 

  client:
    build: ./client
    container_name: client_c
    ports:
      - '3500:3500'
    stdin_open: true   
    tty: true
    
   